### ISSUE TITLE
Can we get a configuration for crusher?

### ISSUE THREAD

**Issue by psakievich** [olcf/spack-environments#3]
Will this be updated for crusher and frontier when it becomes available?

**Comment by jfinney10** [comment]
Initial Crusher environment template was added [here](https://github.com/olcf/spack-environments/commit/26c797188bb025cb8b09981cfc5c85344af255b1).

A Frontier environment will be created once the system is available and the environment is stable.  We recommend using the module files as external packages in a spack environment in the meantime to speed up your development if you already have access.

Let me know if you have any issues with the Crusher template.

**Comment by psakievich** [comment]
Thanks!
